worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  sendfile    on;
  tcp_nopush  on;

  # Gzip HLS playlists
  gzip            on;
  gzip_types      application/vnd.apple.mpegurl;

  server {
    listen 80;
    root /html/;
    index index.html;

    # HLS segments and playlists
    location /hls/ {
      types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
      }

      add_header Cache-Control "no-cache";
      add_header Access-Control-Allow-Origin *;
    }
  }
}

rtmp {
  server {
    listen 1935;
    chunk_size 4000;

    application live {
      live on;

      # HLS output
      hls on;
      hls_path /html/hls/;
      hls_fragment 3s;
      hls_playlist_length 18s;

      # Disable consuming the stream from nginx as RTMP
      allow play 127.0.0.1;
    }
  }
}
